Remove non-ASCII characters from README.rst
Replace the 2 EN-DASH (https://www.compart.com/en/unicode/U+2013) characters in
README.rst with the ASCII character HYPNEN-MINUS
(http://www.fileformat.info/info/unicode/char/2d/index.htm).  Strictly speaking,
the EN-DASH character is more correct but using a non ASCII character can lead 
to problems when installing the package like exception thrown by pip running
setup.py like 

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1200:
ordinal not in range(128)

Of course the problem itself is probably due to the environment for whatever
reason not supporting UTF-8 and/or the setup.py script, but this is all probably
irrelevant and causing undue stress to the end-user wanting to just install this 
package.